# Generated by Django 5.2 on 2025-06-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='sample-blog', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
